version: "3.8"

services:
  gateway-api:
    container_name: gateway-api
    build:
      context: ./Gateway/Gateway.API/Gateway.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-iam:
    container_name: scamsleuth-iam
    build:
      context: ./Services/IAM
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-media:
    container_name: scamsleuth-media
    build:
      context: ./Services/Media
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-user:
    container_name: scamsleuth-user
    build:
      context: ./Services/User
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-admin:
    container_name: scamsleuth-admin
    build:
      context: ./Services/Admin
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-public:
    container_name: scamsleuth-public
    build:
      context: ./Services/Public
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - scamsleuth-network

  scamsleuth-ai:
    container_name: scamsleuth-ai
    build:
      context: ./Services/AI
      dockerfile: Dockerfile
    volumes:
      - ./Services/AI:/app
    ports:
      - "6996:6996"
    environment:
      - mongodb_container
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb_container
      - postgres_container
    networks:
      - scamsleuth-network

  db-handler:
    container_name: db-handler
    build:
      context: ./Services/DB_Handler
      dockerfile: Dockerfile
    volumes:
      - ./Services/DB_Handler:/app
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres_container:5432/ScamSleuth_db
    depends_on:
      - postgres_container
    networks:
      - scamsleuth-network

  postgres_container:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ScamSleuth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - scamsleuth-network

  mongodb_container:
    image: mongo:6
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    networks:
      - scamsleuth-network

  redis_container:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - scamsleuth-network

  rabbitmq_container:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - scamsleuth-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@scamsleuth.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - scamsleuth-network

networks:
  scamsleuth-network:
    driver: bridge
    name: scamsleuth-network

volumes:
  postgres-data:
  mongo-data:
  redis-data:
  pgadmin-data:
