version: '3.8'

services:
  api-gateway:
    build:
      context: ./Gateway/Gateway.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Gateway/Gateway.API:/src
      - /src/bin
      - /src/obj
    networks:
      - microservices-network
    depends_on:
      - iam-service
      - media-service

  iam-service:
    build:
      context: ./Services/IAM
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Services/IAM:/src
      - /src/bin
      - /src/obj
    networks:
      - microservices-network

  media-service:
    build:
      context: ./Services/Media
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Services/Media:/src
      - /src/bin
      - /src/obj
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge