"""auto

Revision ID: d2ba0b603be9
Revises: 
Create Date: 2025-05-06 10:25:03.896796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd2ba0b603be9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First drop foreign keys to avoid dependency issues
    op.drop_constraint('review_review_content_id_fkey', 'review', type_='foreignkey')

    # Then drop tables in the correct order
    op.drop_table('review_content_media')
    op.drop_table('review_content')
    op.drop_table('admin_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_review',
                    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], name='admin_review_admin_id_fkey'),
                    sa.ForeignKeyConstraint(['review_id'], ['review.review_id'], name='admin_review_review_id_fkey'),
                    sa.PrimaryKeyConstraint('admin_id', 'review_id', name='admin_review_pkey')
                    )
    op.create_table('review_content',
                    sa.Column('review_content_id', sa.INTEGER(),
                              server_default=sa.text("nextval('review_content_review_content_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('review_content', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('review_content_id', name='review_content_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('review_content_media',
                    sa.Column('review_content_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['review_content_id'], ['review_content.review_content_id'],
                                            name='review_content_media_review_content_id_fkey'),
                    sa.PrimaryKeyConstraint('review_content_id', 'media_id', name='review_content_media_pkey')
                    )
    op.create_foreign_key('review_review_content_id_fkey', 'review', 'review_content', ['review_content_id'],
                          ['review_content_id'])
    # ### end Alembic commands ###
